config/routes.rb
FirstApp::Application.routes.draw do
 

  match '/rate' => 'rater#create', :as => 'rate'

  get "students/index"

  get "students/show"

 authenticated :student do 
  root :to => "students#show"
end
root :to => "students#index"
devise_for :students
resources :students
resources :houses
resources :profiles
resources :event_notes
resources :ratings
resources :events do
  member do
    post :rate
  end
end
resources :messages
resources :message_boards
resources :invitations do
  member do
    get 'attending'
    post 'attending'
    get 'not_attending'
    post 'not_attending'
  end

end

end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
 # GET /houses
  # GET /houses.json
before_filter :authenticate_student!
  def index
    @houses = House.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @houses }
    end
  end

  # GET /houses/1
  # GET /houses/1.json
  def show
    @house = House.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json {redirect_to :back}
    end
  end

  # GET /houses/new
  # GET /houses/new.json
  def new
    @house = House.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @house }
    end
  end

  # GET /houses/1/edit
  def edit
    @house = House.find(params[:id])
  end

  # POST /houses
  # POST /houses.json
  def create
    puts "in create"
    @house = House.new(params[:house])
    @house.save!
    respond_to do |format|
      if @house.id.nil?
        format.html { render action: "new" }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      else
         format.html { redirect_to @house, notice: 'house was successfully created.' }
        format.json { render json: @house, status: :created, location: @house }
       
      end
    end
  end

  # PUT /houses/1
  # PUT /houses/1.json
  def update
    @house = House.find(params[:id])

    respond_to do |format|
      if @house.update_attributes(params[:house])
        format.html { redirect_to @house, notice: 'house was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.json
  def destroy
    @house = House.find(params[:id])
    @house.destroy

    respond_to do |format|
      format.html { redirect_to houses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/index.html.erb
<h1>Listing Houses</h1>
<%if (@houses) then%>

<table>
  <tr>
    <th>Name</th>
    <th>House Type</th>
  
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @houses.each do |house| %>
<%if house.house_type=="Fraternity" then %>
  <tr>
    <td><%= link_to house.name, house %></td>
    <td><%= house.house_type %></td>
    <div class="links">
   <%end%>
 </tr>
 <%end%>
   <% @houses.each do |house| %>
<%if house.house_type=="Sorority" then %>
  <tr>
    <td><%= link_to house.name, house %></td>
    <td><%= house.house_type %></td>
    <div class="links">
   <%end%>
    <% if current_student.role=="admin" then%>
    <td><%= link_to 'Edit', edit_house_path(house) %></td>
    <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td></div>
    <%end%>
  </tr>
</div>
<% end %>
<% end %>
</table>

app/views/houses/show.html.erb
  <p id="notice"><%= notice %></p>


	<p>
<div id="housename">
  <%= @house.name %>
  </div>
</p>



<p>
<div id="housetype">
  <%= @house.house_type %>
</div>
</p>

<br>
<br>
<br>
<p><b><%=@house.name%> Roster</b></p>
<div id ="accordion">
	<h3>2013</h3>
	<div>
	<table id= "roster">
	<tr>

		<th>Name</th>
		<th>Email</th>
		<th>Gender</th>
		<th>Pledge Class</th>
	</tr>
	
	<% @house.students.each do |student| %>
	<% if student.pledge_class=="2013" then %>
	<tr>
		<td><%= student.capitalize_name%></td>
		<td><%= student.email%></td>
		<td><%= student.gender%></td>
		<td><%= student.pledge_class%></td>
		 <div class="links"><td><%= link_to 'View Person', student_path(student) %></td></div>
	</tr>
	<%end%>
	<% end %>
</table>
</div>
<h3>2014</h3>
<div>
	<table id= "roster">
	
	<tr>

		<th>Name</th>
		<th>Email</th>
		<th>Gender</th>
		<th>Pledge Class</th>
	</tr>
	<% @house.students.each do |student| %>
	<% if student.pledge_class=="2014" then %>
	<tr>
		<td><%= student.capitalize_name%></td>
		<td><%= student.email%></td>
		<td><%= student.gender%></td>
		<td><%= student.pledge_class%></td>
		 <div class="links"><td><%= link_to 'View Person', student_path(student) %></td></div>
	</tr>
	<% end %>
	<% end %>
</table>
</div>
<h3>2015</h3>
<div>
	<table id= "roster">
	
	<tr>

		<th>Name</th>
		<th>Email</th>
		<th>Gender</th>
		<th>Pledge Class</th>
	</tr>
	<% @house.students.each do |student| %>
	<% if student.pledge_class=="2015" then %>
	<tr>
		<td><%= student.capitalize_name%></td>
		<td><%= student.email%></td>
		<td><%= student.gender%></td>
		<td><%= student.pledge_class%></td>
		 <div class="links"><td><%= link_to 'View Person', student_path(student) %></td></div>
	</tr>
	<% end %>
	<% end %>
</table>
</div>
<h3>2016</h3>
<div>
	<table id= "roster">
	
	<tr>

		<th>Name</th>
		<th>Email</th>
		<th>Gender</th>
		<th>Pledge Class</th>
	</tr>
	<% @house.students.each do |student| %>
	<% if student.pledge_class=="2016" then %>
	<tr>
		 <div class="links"><td><%= link_to student.capitalize_name, student_path(student) %></td></div>
		<td><%= student.email%></td>
		<td><%= student.gender%></td>
		<td><%= student.pledge_class%></td>
		
	</tr>
	<% end %>
	<% end %>
</table>
</div>
<h3>2017</h3>
<div>
	<table id= "roster">
	
	<tr>

		<th>Name</th>
		<th>Email</th>
		<th>Gender</th>
		<th>Pledge Class</th>
	</tr>
	<% @house.students.each do |student| %>
	<% if student.pledge_class=="2017" then %>
	<tr>
		<td><%= student.capitalize_name%></td>
		<td><%= student.email%></td>
		<td><%= student.gender%></td>
		<td><%= student.pledge_class%></td>
		 <div class="links"><td><%= link_to 'View Person', student_path(student) %></td></div>
	</tr>
	<% end %>
	<% end %>
</table>
</div>
</div>
<br />

<table id= "invitations">
	<% if current_student.house==@house then %>
	<th>Pending Invitations</th>
	<tr>

		<th>Event</th>
		<th>Response</th>
	</tr>
	<% @house.invitations.each do |invitation| %>
	<tr>
		 <div class="links"><td><%= link_to invitation.event.name, invitation.event%></td></div>
		<div id="response"><td><%= invitation.response%></td></div>
		
		 <div class="links"><td><%= link_to 'View Invitation', invitation_path(invitation) %></td></div>
		<%if current_student.role == "Social Chair" then %>
		<td><%= form_for invitation, :remote => true do |f|%>
			<%= f.label :response, "Response"%><br/>
			<%=f.select :response, ["Yes", "No"]%>
			<%=f.submit "Respond to invite"%>
			
			<%end%>
			<%end%>
		</td>
	</tr>
	<%end%>
	
	<%end%>
</table>

<br>
<br>
<table id="events">
	<th>Event Information</th>
	
	<%= calendar @house.events do |event| %>
	<%if @house==current_student.house then%>
   <div class="eventlinks"><div> <%=link_to event.name, event %></div></div>
  <div><%= event.start_time.time.to_s(:time) %></div>
<%else%>
 <div class="eventlinks"><div> Unavailable</div></div>
  <div><%= event.start_time.time.to_s(:time)   %></div>
<%end%>
<%end%>
	</table>
	<% if current_student.house==@house then %>
	<% if current_student.role=="Social Chair" then%>
	<div class="form">
	<%= form_for Event.new do|f| %>
		<%=f.label :name, "Name" %><br />
		<%=f.text_field :name, :id => "name" %><br />
		<%=f.label :location, "Location" %><br />
		<%=f.text_field :location, :id => "location" %><br />
		<%=f.label :description, "Description" %><br />
		<%=f.text_field :description, :id => "description"%><br />
		<%=f.label :start_time, "Date"%><br />
		<%=f.date_select :start_time %><br />
		<%=f.label :start_time, "Time"%><br />
		<%=f.time_select :start_time, :ignore_date => true %><br />
		<%=f.label :event_type, "Type" %><br />
		<%=f.select :event_type, ["Pregame", "Exchange", "Philanthropy"]%><br />
		<%= f.hidden_field :house_id, :value => @house.id %><br />
	
		<br>
		<%= f.submit "Add Event" %>
	<%end%>
</div>
	<%end%>
	<%end%>

	<br>		
	<br>
	<br>
	


<script>
  $(function() {
    $( "#accordion" ).accordion();
  });
  </script>

app/views/houses/update.js.erb
$("#houses_invitations").html("<tr><td><%= @invitation.event.name%></td><td><%=@invitation.response%></td></tr>")
$("#name").val('')
$("#location").val('')
$("#description").val('')