config/routes.rb
FirstApp::Application.routes.draw do
 

  match '/rate' => 'rater#create', :as => 'rate'

  get "students/index"

  get "students/show"

 authenticated :student do 
  root :to => "students#show"
end
root :to => "students#index"
devise_for :students
resources :students
resources :houses
resources :profiles
resources :event_notes
resources :ratings
resources :events do
  member do
    post :rate
  end
end
resources :messages
resources :message_boards
resources :invitations do
  member do
    get 'attending'
    post 'attending'
    get 'not_attending'
    post 'not_attending'
  end

end

end

app/models/student.rb
class Student < ActiveRecord::Base
  letsrate_rater
  rolify
  after_create :default_role
  make_voter
  ROLES = ['Student', 'Social Chair']
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_one :profile
belongs_to :house
has_many :ratings
has_many :rated_events, :through => :ratings, :source => :events
has_many :messages, dependent: :destroy
has_many :event_notes, dependent: :destroy
has_and_belongs_to_many :roles, :join_table => :students_roles
 
  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :gender, :email, :pledge_class, :password, :password_confirmation, :remember_me, :house_id, :role
attr_accessible :role_ids, :as => :admin
validates :name, :password, :password_confirmation, :email, :gender, presence: true
  validates :password, :password_confirmation, length: {in: 6..15}
  validates :email, uniqueness: true
  validates :password, confirmation: true
    # attr_accessible :title, :body

def self.search(search)
	search.present? and all(:conditions =>['name LIKE ? OR email LIKE ?', "%#{search.strip}%", "%#{search.strip}%"])
end
def default_role
  self.roles << Role.where(:name => 'Student').first
end
def feed
  Message.findall
end
def role?(role)
  return  !!self.roles.find_by_name(role.to_s.camelize)
end
 def capitalize_name
    "#{name.titleize}"
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_filter :authenticate_student!
  before_filter :only_allow_admin, :only => [:index]
  def index
  	
  	@students=Student.search(params[:search])
  	respond_to do |format|
  		format.html
  		format.json{ render json: @students}
  end

end
 def show
if params[:id].nil? 
    @student = current_student
else 
    @student = Student.find params[:id]
end
  	
  	@messages=@student.messages.paginate(page: params[:page])
  	
  	respond_to do |format|
  		format.html
  		format.json {render json: @student}
  end
end
def new
	@student = Student.new
	respond_to |format|
	format.html
	format.json { render json: @student}

end
def edit
	@student = Student.find(params[:id])
	@student.house_id=House.find(params[:student][:house_id])
	@student.save!
end
def create
	@student=Student.create_new(params[:student])
	@student.save!
	@profile=Profile.create_new(params[:profile])
	@profile.student_id=@student.id
	@profile.save!
	respond_to do |format|
		if @student.id.nil?
			format.html {render action: "new"}
			format.json {render json: @studnet.errors, status: :unprocessable_entity}
		else
			format.html {redirect to @studnet, notice: "Student was successfully created."}
			format.json {render json: @student, status: :created, location: @student}
		end
	end
end
def update
	@student=Student.find(params[:id])
	@student.house_id=House.find(params[:student][:house_id])
	logger.info "house id is #{params[:student].inspect}"
	@student.save!
	respond_to do |format|
		if @student.update_attributes(params[:student])
			format.html {redirect_to @student, notice: 'Student was successfully updated.'}
			format.json {head :no_content}
		else
			format.html {render action: "edit"}
			format.json	{render json: @student.errors, status: :unprocessable_entity}
		end
	end
end
def destroy
	@student=Student.find(params[:id])
	@student.destroy
	respond_to do |format|
		format.html {redirect_to :back}
		format.json {head :no_content}
	end
end
private 
def only_allow_admin
	redirect_to houses_path, :alert => 'Not authorized as an administrator.' unless current_student.has_role? :admin
end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :gender%><br />
    <%= f.text_field :gender%>
  </div>

  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="role-options-<%= student.id %>" class="modal" style="display: none;">
  <%= simple_form_for student, :url => student_path(student), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline' %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/students/edit.html.erb
<h1>Editing Student</h1>
<%= render 'form' %>
<%= link_to 'Back', @student %>

app/views/students/index.html.erb
<h1>Listing Students</h1>
<%= form_tag students_path, :method => 'get' do %>
	<p>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search", :name => nil %>
	</p>
	<%end%>
	<% if (@students) then %>
	<table>
		<tr>
			<th>Name</th>
	
			<th>Email</th>
			<th>Registered</th>
			<th>Role</th>
		</tr>
		<% @students.each do |student| %>
		<tr>
			<td><%=link_to "#{student.capitalize_name}", student %></td>
			<td><%=student.email%></td>
			<td><%=student.created_at.to_date%></td>
			<td><%=student.roles.first.name.titleize unless student.roles.first.nil?%></td>
			
        </td>
			 <div class="links"><td><%=link_to 'Show', student%> </td>
			<td><%= link_to 'Edit', edit_student_path(student) %></td>
			<td><%= link_to 'Destroy', student, method: :delete, data: {confirm: 'Are You Sure>'} unless student ==current_student %></td></div>
		</tr>
		<% end %>
		<% end %>
	</table>
	<br />
	<br />

app/views/students/show.html.erb
<h3><%= @student.capitalize_name %></h3>
<p><b>Role:</b> <%=@student.role%></p>
<p><b>Email:</b> <%= @student.email%></p>
<p><b>House:</b> <%= link_to @student.house.name, @student.house %></p>

<p><b>Pledge Class:</b> <%= @student.pledge_class %></p>
	<p><b>Events This Month:</b></p>
	<% @student.house.events.each do |event| %>
	<%if event.start_time.mon==Time.now.mon then%>
	<p><%= link_to event.name, event%></p>
	<%end%>
	<%end%>
<br>
<br>
<br>

<% if @student.profile %>
<b>Profile</b>
<table id="profile">
	<tr>
		<%if @student.profile.birthday then%>
		<th>Birthday</th>
		<%end%>
		<th>Interests</th>
		<th>Phone</th>
		<th>Relationship Status</th>
		
	</tr>

	<tr>
	<%if @student.profile.birthday then%>
		<td><%= @student.profile.birthday.to_formatted_s(:long_ordinal) %></td><%end%>
		<td><%= @student.profile.interests %></td>
		<td><%= @student.profile.phone %></td>
		<td><%= @student.profile.relationship_status %></td>
		<%if current_student.id==@student.id then %>
		<td><%=link_to "Edit", edit_profile_path(@student.profile)%></td>
		<%end%>
	
	</tr>
	</table>
	<%else%>
	<%if current_student.id==@student.id then %>
	<b>Profile Empty</b>
</br></br><%=button_to "Create Profile", new_profile_path, :method => :get%>
<%end%>
<%end%>
<br>
<br>
<br>

	<%if @student.messages.any? %>
	<div class="student messages">
	<h3><%=@student.capitalize_name%>'s Messages (<%= @student.messages.count%>) </h3>
	<ol class="messages">
		<%= render @messages %>
	</ol>
	<%=will_paginate @messages %>
	<%end%>
</div>