config/routes.rb
FirstApp::Application.routes.draw do
 

  match '/rate' => 'rater#create', :as => 'rate'

  get "students/index"

  get "students/show"

 authenticated :student do 
  root :to => "students#show"
end
root :to => "students#index"
devise_for :students
resources :students
resources :houses
resources :profiles
resources :event_notes
resources :ratings
resources :events do
  member do
    post :rate
  end
end
resources :messages
resources :message_boards
resources :invitations do
  member do
    get 'attending'
    post 'attending'
    get 'not_attending'
    post 'not_attending'
  end

end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(student)
    student ||= Student.new # guest user (not logged in)
    if student.admin?
      can :manage, :all
    elsif student.social_chair?
        can :manage, :event, :host_id=>student.house_id
    elsif student.student?
        can :read, :all
    end
  end

  def current_ability
    @current_ability ||= case
                            when current_student
                                UserAbility.new(current_student)
                            when current_admin
                                AdminAbility.new
                            else 
                                GuestAbility.new
                            end
    end
    
  
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end

app/models/event.rb
class Event < ActiveRecord::Base
	letsrate_rateable "fun", "drinks", "music", "people"
	has_and_belongs_to_many :houses, :uniq => true
	has_many :ratings
	has_many :raters, :through => :ratings, :source => :students
	has_many :invitations
	has_many :event_notes
  attr_accessible :description, :location, :name, :event_type, :house_id, :host_id, :start_time

def average_rating 
	@value=0
	self.ratings.each do |rating|
		@value=@value +rating.value
	end
	@total=self.ratings.size
	@value.to_f / @total.to_f
end


end

app/models/event_note.rb
class EventNote < ActiveRecord::Base
  attr_accessible :content, :student_id, :event_id

  belongs_to :student
  belongs_to :event
  validates :student_id, presence: true
 
  validates :content, presence: true, length: {maximum: 150}
  default_scope order: 'event_notes.created_at DESC'

 

end

app/models/house.rb
class House < ActiveRecord::Base
	default_scope order("name")
	has_and_belongs_to_many :events, :uniq => true
	has_many :students
	has_many :invitations
  attr_accessible :location, :name, :house_type
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
	make_voteable
	belongs_to :house
	belongs_to :event
  attr_accessible :event_id, :house_id, :response
end

app/models/message.rb
class Message < ActiveRecord::Base
	
  attr_accessible :content, :student_id
  belongs_to :student
  validates :student_id, presence: true
 
  validates :content, presence: true, length: {maximum: 150}
  default_scope order: 'messages.created_at DESC'

  
end

app/models/person.rb
class Person < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :gender, :house_id, :email, :password, :password_confirmation, :remember_me
	has_one :profile
	belongs_to :house
  validates :name, :password, :password_confirmation, :email, :gender, presence: true
  validates :password, :password_confirmation, length: {in: 6..15}
  validates :email, uniqueness: true
  validates :password, confirmation: true
#  validates_each :email do |record, attr, value|
  #	record.errors.add(attr, 'must be valid email address') if value != ^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$
#end
def self.create_new(params)
  student=Student.new(params)
  if student.save then
  logger.info "student saved: #{student.inspect}"
  end
  return student
end

def self.search(search)
	search.present? and all(:conditions =>['name LIKE ? OR email LIKE ?', "%#{search.strip}%", "%#{search.strip}%"])
end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :student
  attr_accessible :birthday, :interests, :student_id, :phone, :relationship_status
  #validates :person_id, uniqueness: true
def self.create_new(params)
	profile=Profile.new(params)
	if profile.save then
	logger.info "profile saved: #{profile.inspect}"

end
return profile
end
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  attr_accessible :event_id, :sudent_id, :value
  belongs_to :event
  belongs_to :student
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :students, :join_table => :students_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/sorority.rb
class Sorority < ActiveRecord::Base
	has_many :people
  attr_accessible :location, :name
end

app/models/student.rb
class Student < ActiveRecord::Base
  letsrate_rater
  rolify
  after_create :default_role
  make_voter
  ROLES = ['Student', 'Social Chair']
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_one :profile
belongs_to :house
has_many :ratings
has_many :rated_events, :through => :ratings, :source => :events
has_many :messages, dependent: :destroy
has_many :event_notes, dependent: :destroy
has_and_belongs_to_many :roles, :join_table => :students_roles
 
  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :gender, :email, :pledge_class, :password, :password_confirmation, :remember_me, :house_id, :role
attr_accessible :role_ids, :as => :admin
validates :name, :password, :password_confirmation, :email, :gender, presence: true
  validates :password, :password_confirmation, length: {in: 6..15}
  validates :email, uniqueness: true
  validates :password, confirmation: true
    # attr_accessible :title, :body

def self.search(search)
	search.present? and all(:conditions =>['name LIKE ? OR email LIKE ?', "%#{search.strip}%", "%#{search.strip}%"])
end
def default_role
  self.roles << Role.where(:name => 'Student').first
end
def feed
  Message.findall
end
def role?(role)
  return  !!self.roles.find_by_name(role.to_s.camelize)
end
 def capitalize_name
    "#{name.titleize}"
  end
end

app/helpers/events_helper.rb
module EventsHelper
def rating_ballot
	if @rating = current_student.ratings.find_by_event_id(params[:id])
		@rating
	else
		current_student.ratings.new
	end
end
def current_student_rating
	if @rating=current_student.ratings.find_by_event_id(params[:id])
		@rating.value
	else
		"N/A"
	end
end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/invitation_helper.rb
module InvitationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <% if student_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_student_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_student_session_path %>
    </li>
  <% end %>
  <% if student_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_student_registration_path %>
    </li>
    <li>
    <%= link_to current_student.capitalize_name, student_path(current_student.id) %>
  </li>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_student_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application.js" %>

  

  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
  <%= csrf_meta_tags %>
</head>

  <body class="<%= controller_name %> <%= action_name %>">
    <div id="container" class="container">
      <header>
        <%= render 'layouts/navigation' %>
        <%= render 'layouts/messages' %>
        <div id="messageboard"><p><%= link_to "message board", messages_path %>    &nbsp&nbsp&nbsp<%= link_to "houses", houses_path %></p></div>
        <div id="title">GREEKILLINI</div>
      </header>
      <div id="main" role="main">
        <%= yield %>
      </div>

      <footer>

      </footer>
    </div> <!--! end of #container -->
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="messages">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  
 
  <span class="content"><%= feed_item.content %></span>
   
  <span class="timestamp">
    Posted by <%= link_to feed_item.student.name, feed_item.student %> <%=  time_ago_in_words(feed_item.created_at) %> ago.
  </span>
   <%= link_to "delete", feed_item, method: :delete, data: { confirm: "Are You sure?" } %>

 
</li>